apiVersion: cloudhypervisor.quill.today/v1beta1
kind: VirtualMachineMigration
metadata:
  labels:
    app.kubernetes.io/name: ch-vmm
    app.kubernetes.io/managed-by: kustomize
  name: virtualmachinemigration-sample
spec:
  # TODO(user): Add fields here
