apiVersion: cloudhypervisor.quill.today/v1beta1
kind: VirtualMachine
metadata:
  labels:
    app.kubernetes.io/name: ch-vmm
    app.kubernetes.io/managed-by: kustomize
  name: virtualmachine-sample
spec:
  # TODO(user): Add fields here
