# permissions for end users to view virtualmachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ch-vmm
    app.kubernetes.io/managed-by: kustomize
  name: virtualmachine-viewer-role
rules:
- apiGroups:
  - cloudhypervisor.quill.today
  resources:
  - virtualmachines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudhypervisor.quill.today
  resources:
  - virtualmachines/status
  verbs:
  - get
