# permissions for end users to edit virtualmachinemigrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ch-vmm
    app.kubernetes.io/managed-by: kustomize
  name: virtualmachinemigration-editor-role
rules:
- apiGroups:
  - cloudhypervisor.quill.today
  resources:
  - virtualmachinemigrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudhypervisor.quill.today
  resources:
  - virtualmachinemigrations/status
  verbs:
  - get
