apiVersion: v1
kind: ConfigMap
metadata:
  name: daemon-config
  namespace: ch-vmm-system 
data:
  daemon-conf.yaml: |
    grpc_port: 8443
    tls_config:
      server_name: "ch-vmm-daemon.ch-vmm-system.svc"
      key_file: "/var/lib/virtmanager/daemon/cert/tls.key"
      cert_file: "/var/lib/virtmanager/daemon/cert/tls.crt"
      ca_file: "/var/lib/virtmanager/daemon/cert/ca.crt"