apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ch-vmm-daemon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ch-vmm-daemon
subjects:
  - kind: ServiceAccount
    name: ch-vmm-daemon
    namespace: ch-vmm-system
