apiVersion: v1
kind: Service
metadata:
  name: ch-vmm-daemon
  namespace: ch-vmm-system
spec:
  clusterIP: None
  selector:
    name: ch-vmm-daemon
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443