# This rule is not used by the project virtmanager itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over cloudhypervisor.quill.today.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: virtmanager
    app.kubernetes.io/managed-by: kustomize
  name: vmpool-admin-role
rules:
- apiGroups:
  - cloudhypervisor.quill.today
  resources:
  - vmpools
  verbs:
  - '*'
- apiGroups:
  - cloudhypervisor.quill.today
  resources:
  - vmpools/status
  verbs:
  - get
