# This rule is not used by the project ch-vmm itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to cloudhypervisor.quill.today resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ch-vmm
    app.kubernetes.io/managed-by: kustomize
  name: vmset-viewer-role
rules:
- apiGroups:
  - cloudhypervisor.quill.today
  resources:
  - vmsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudhypervisor.quill.today
  resources:
  - vmsets/status
  verbs:
  - get
