# permissions for end users to view vmsnapshots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ch-vmm
    app.kubernetes.io/managed-by: kustomize
  name: vmsnapshot-viewer-role
rules:
- apiGroups:
  - cloudhypervisor.quill.today
  resources:
  - vmsnapshots
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudhypervisor.quill.today
  resources:
  - vmsnapshots/status
  verbs:
  - get
