name: release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: docker.io
          username: nalajalanaresh
          password: ${{ secrets.DOCKERHUB_TOKEN }}
       


      - id: build_ch_vmm_prerunner
        uses: docker/build-push-action@v6
        with:
          file: build/ch-vmm-prerunner/Dockerfile.ch
          build-args: |
            GITHUB_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }}
          tags: nalajalanaresh/ch-vmm-prerunner:${{ steps.get_version.outputs.version }}
          platforms: linux/amd64
          push: true
      

      - uses: docker/build-push-action@v6
        with:
          file: build/ch-vmm-controller/Dockerfile
          build-args: |
            PRERUNNER_CH_IMAGE=nalajalanaresh/ch-vmm-prerunner:${{ steps.get_version.outputs.version }}
            GITHUB_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }}
          tags: nalajalanaresh/ch-vmm-controller:${{ steps.get_version.outputs.version }}
          platforms: linux/amd64
          push: true

      - uses: docker/build-push-action@v6
        with:
          file: build/ch-vmm-daemon/Dockerfile
          build-args: |
            GITHUB_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }}
          tags: nalajalanaresh/ch-vmm-daemon:${{ steps.get_version.outputs.version }}
          platforms: linux/amd64
          push: true

      - uses: docker/build-push-action@v6
        with:
          file: build/virtmanager-container-disk-base/Dockerfile
          tags: nalajalanaresh/virtmanager-container-disk-base
          platforms: linux/amd64
          push: true

      - uses: docker/build-push-action@v6
        with:
          file: build/virtmanager-kernel-base/Dockerfile
          tags: nalajalanaresh/virtmanager-kernel-base
          platforms: linux/amd64
          push: true

      - uses: docker/build-push-action@v6
        with:
          file: build/virtmanager-container-rootfs-base/Dockerfile
          tags: nalajalanaresh/virtmanager-container-rootfs-base
          platforms: linux/amd64
          push: true

      - run: |
          curl -sLo /tmp/skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          chmod +x /tmp/skaffold
          /tmp/skaffold render --default-repo=nalajalanaresh --offline=true -t $GITHUB_REF_NAME > ch-vmm.yaml

      - uses: softprops/action-gh-release@v2
        with:
          files: ch-vmm.yaml
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}